# Generated by Django 5.0.7 on 2024-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_category_is_active_gallery_is_active_menu_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="image_url",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_images/"
            ),
        ),
    ]
